### PR TITLE
(Assert_Greater): fix output message to show the operator

### PR DESCRIPTION
**Pull request by briot**

### CODE REVIEW

**Comment by briot** [comment]
I believe this small patch is ready for commit

**Comment by pmderodat** [comment]
You are right, thank you for the ping! It’s in the pipe, we’ll take care of it shortly.

**Comment by anisimkov** [comment]
I'm in process of #25 accept, I saw the same changes there. Is it repeat or addition ?

**Comment by anisimkov** [comment]
Yes, there is the same commit in #25

**Comment by anisimkov** [comment]
Opps, I did not know that we have 
adacore-bot  merging the commits.

**Pull request merged**
