### PR TITLE
(Time_Value): do not ignore fractions of seconds when parsing time

### PR DESCRIPTION
**Pull request by briot**

### CODE REVIEW

**Comment by briot** [comment]
Given you accepted the change, I think your comment might be OBE, but still:
We do want to multiply by 0.1. Let's assume we are parsing "0.123"
We have the following steps:

* Subsecond = 0.0
* reading "3"
  subsecond = (0.0 + 3) *0.1 = 0.3
* reading "2"
  subsecond = (0.3+2) * 0.1 = 0.23
* reading "1"
  subsecond = (0.23 + 1) * 0.1 = 0.123

**Comment by anisimkov** [comment]
Yes, I undestood, thank you for additional explanation. The commit on the way to approve.

**Comment by pmderodat** [comment]
Hello Manu,

Thank you for your contribution! Could you please add a test for this enhancement? You can have a look at https://github.com/AdaCore/gnatcoll-core/tree/master/testsuite/tests/utils to see how this should be done.

Of course, we are here to help if you need assistance with the testsuite. :-) Thank you in advance!

**Comment by briot** [comment]
> Thank you for your contribution! Could you please add a test for this enhancement? You can have a look at https://github.com/AdaCore/gnatcoll-core/tree/master/testsuite/tests/utils to see how this should be done.
> 
> Of course, we are here to help if you need assistance with the testsuite. :-) Thank you in advance!

Sorry, I cannot.
We are using a much older version of GNATCOLL, and I never setup what’s needed to run the
testsuite (nor do I have the time to do that…)

I honestly consider this is part of AdaCore’s job to do that when customers take the time to
file patches. Quality control is actually the reason we are paying AdaCore in the first place.

Manu

**Comment by pmderodat** [comment]
What you suggest is a very inefficient way to work: commit authors are the best persons to know what their changes do and how to test them properly. Actually testcases help the review process as they provide examples to understand the bug that is fixed or the new features that are added.

For these reasons, all contributions we receive on GitHub must conform to our [contribution guidelines](https://github.com/AdaCore/gnatcoll-core/blob/master/CONTRIBUTING.md) in order to be accepted. If you want your patches to be handled as part of your support contract, please go through GNATtracker.

Thank you in advance,

**Comment by briot** [comment]
Forget about the patch then. I was just trying to help.

**Pull request closed without merging**
