### PR TITLE
Remove unused and obsolete pngmath sphinx extension

### PR DESCRIPTION
**Pull request by asarhaddon**
Bug-Debian: https://bugs.debian.org/918816

### CODE REVIEW

**Comment by anisimkov** [comment]
This commit is conflicting with upcoming conf.py style fixes. I can repeat this change myself or you can wait and resolve this conflict after your previous 4 commits approved. What do you prefer?

**Comment by asarhaddon** [comment]
To be honest, I fail to understand your answer.
What conf.py changes? (maybe in a private branch that I cannot see?)
What previous commits? (maybe the unrelated merge requests created the same day?)
However, as long as the fix is applied, I do not mind in which branch this happens.

**Comment by anisimkov** [comment]
(maybe in a private branch that I cannot see?)Yes. I had to do some style fixes in conf.py to apply your modification on it.

**Comment by anisimkov** [comment]
The fix is not applied, but in process of AdaCore review.

**Comment by anisimkov** [comment]
Close the pull request please, your commit already in the repository.

**Pull request closed without merging**
