### PR TITLE
Added library_type to readme that gprbuild complains is missing

### PR DESCRIPTION
**Pull request by theJosher**

### CODE REVIEW

**Comment by theJosher** [comment]
Not sure what "or" is... I can't get gnatcoll-core to build on windows anyhow using the two methods described in the readme (gnat 2018 is installed and in the path):

`>gprbuild gnatcoll.gpr
gnatcoll.gpr:36:04: no value defined for "build"
gnatcoll.gpr:36:26: undefined external reference "BUILD"
gnatcoll.gpr:39:04: no value defined for "library_type"
gnatcoll.gpr:39:40: undefined external reference "LIBRARY_TYPE"
gprbuild: "gnatcoll.gpr" processing failed`

`>make prefix=/opt/libgnatcoll BUILD=DEBUG install
which: no gnatls in (C:\GNAT\2018\bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files\Tools\shell.w32-ix86;C:\Users\joshu\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\joshu\AppData\Local\Microsoft\WindowsApps;C:\Users\joshu\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;)
cat: /version_information: No such file or directory
gprinstall -p -f --target=x86_64-windows -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION= -XGNATCOLL_OS= -XBUILD=DEBUG --relocate-build-tree --sources-subdir=include/gnatcoll --prefix=/opt/libgnatcoll -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
        --build-name=static -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION= -XGNATCOLL_OS= -XBUILD=DEBUG \
        --build-var=LIBRARY_TYPE --build-var=GNATCOLL_BUILD \
        --build-var=GNATCOLL_CORE_BUILD /gnatcoll.gpr
gprinstall.exe: project file "/gnatcoll.gpr" not found in .;
make: *** [install-static] Error 4`

**Comment by theJosher** [comment]
Thanks, and sorry for that. If I want to use make instead, which version of make should I use? The [most relevant docs I could find](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/building_executable_programs_with_gnat.html#using-the-gnu-make-utility) say GNU make, and right now I'm using GNU make 3.76.1d. It seems to have difficulty knowing to create directories, and maybe that's just the tip of the iceberg.

`>make setup
which: no gnatls in (C:\GNAT\2018\bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files\Tools\shell.w32-ix86;C:\Users\joshu\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;;C:\Program Files\Microsoft VS Code\bin;C:\Users\joshu\AppData\Local\Microsoft\WindowsApps;C:\Users\joshu\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;)
cat: /version_information: No such file or directory`

**Comment by t-14** [comment]
> which: no gnatls in (C:\GNAT\2018\bin (...)

You certainly won't get very far with the makefile given such a severe issue. Make sure your environment is properly set up (in particular "which" can find your toolchain) before going any further. The following makefile must succeed:

```
all:
	echo $(dir $(shell which gnatls))
```

If you want to call gprbuild directly - you can, but then you need to call exactly the command found in the makefile, rather that just `gprbuild gnatcoll.gpr` like the readme optimistically says. We will remove this recommendation entirely and only keep the one that uses the makefile.

**Comment by pmderodat** [comment]
Hello,
We just updated the README according to the above, so we’ll close this PR as obsolete: thank you for raising the issue! If you still have trouble building GNATCOLL, please open a separate GitHub issue, thanks!

**Pull request closed without merging**
